### PR TITLE
Add file for user specific settings

### PR DESCRIPTION
**Pull request by fflorent**
## Problem

- See #47 (allow the user to override the default settings)

## Solution

- add a `settings.user.js` file to let the user override the default settings
- change the `settings.js` file to load the `settings.user.js`
- make this file read-only

## PR Status

- [x] Code finished and ready to be reviewed/tested (checked by overriding the editor theme)
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by fflorent** [comment]
!testme

**Comment by tituspijean** [comment]
Can you share some example of config in the user file? I have tried tweaking mine and restarting the service, but it looks like it ignores my settings.

**Comment by fflorent** [comment]
> Can you share some example of config in the user file? I have tried tweaking mine and restarting the service, but it looks like it ignores my settings.

I shared some example in the comments of `settings.user.js`, you can also take a look at `DESCRIPTION.md`.

Otherwise, here are my `settings.user.js` for tests:
```js
module.exports = (defaultSettings) => ({
    /**
     * Put here your own config, it will override the ones in settings.js
     *
     * Example:
     * ```js
     * module.exports = (defaultSettings) => ({
     *     lang: "de", // define the language as "de"
     *     exportGlobalContextKeys: true, // override the `exportGlobalContextKeys` value
     *
     *
     *     logging: { // replace the default logging option
     *         ...defaultSettings.logging, // this will reinject the default settings in logging
     *         console: {
     *             ...defaultSettings.logging.level, // this will reinject the default settings in logging.console
     *             level: "debug", // but here, we override the "info" level by "debug"
     *         },
     *     },
     * });
     * ```
     */
    editorTheme: {
        ...defaultSettings.editorTheme,

        codeEditor: {
            lib: "monaco",
            options: {
                ...defaultSettings.editorTheme.codeEditor.options,
                theme: "tomorrow-night",
            },
        },
    },
});
```

The result looks like this:
image


Can you share yours?

**Comment by tituspijean** [comment]
Nah it's all good, I made a typo that's why.

🚀

**Pull request merged**
