### PR TITLE
Upgrade to v1.3.4 and add update_version.sh

### PR DESCRIPTION
**Pull request by tituspijean**

### CODE REVIEW

**Comment by tituspijean** [comment]
[Test Badge](https://ci.pijean.ovh/ci/job/10)

**Comment by tituspijean** [comment]
[Test Badge](https://ci.pijean.ovh/ci/job/11)

**Review by ericgaspar — APPROVED** [review]
Are you setting up an upgrade bot?  🤖

**Comment by tituspijean** [comment]
I am lazy and curious, so yes. 😇

**Pull request merged**
